set encoding=utf-8

set nolangremap

set backspace=indent,eol,start
set whichwrap+=[,],<,>

set autoread
set nofixendofline

set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=-1

set autoindent
set smartindent

set formatoptions+=j

set ignorecase
set smartcase
set hlsearch
set incsearch
set tagcase=followscs

set completeopt=menuone,preview,noinsert,noselect
set wildignorecase

set wildmenu
set wildoptions=tagfile
if has("nvim")
    set wildoptions+=pum
endif

" <https://gist.github.com/XVilka/8346728>
if has("termguicolors") && expand("$COLORTERM") =~# "truecolor\\|24bit"
    set termguicolors

    if has("nvim")
        set winblend=30
        set pumblend=30
    else
        let &t_8f = "\e[38;2;%lu;%lu;%lum"
        let &t_8b = "\e[48;2;%lu;%lu;%lum"
    endif
endif

set cursorline
set display=lastline
set number
set relativenumber

" DECSCUSR(+ vertical, blinking)
" <https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_>
if !has("nvim") && &term =~? "xterm\\|konsole\\|alacritty\\|st"
    let &t_EI = "\e[2 q" " normal mode  = block
    let &t_SI = "\e[5 q" " insert mode  = vertical, blinking
    let &t_SR = "\e[4 q" " replace mode = horizontal
endif
set guicursor=n-v-c:block,i-ci-sm:ver1-blinkwait500-blinkon500-blinkoff500,r-cr-o:hor1

set visualbell
set belloff=all

set list
set listchars=tab:>.,trail:&

" filename[modified][readonly]    [line/lines, column](\U"codepoint")[filetype]
set statusline=%t%m%r%=[%l/%L,\ %c](\\U%B)%y
set laststatus=2
set showcmd

set title
set titlestring=%F%m%r\ -\ %{v:progname}

set splitright
set helpheight=0
set scrolloff=5

set report=0
set shortmess=aoOc

if has("osxdarwin")
    set clipboard=unnamed
else
    set clipboard=unnamedplus
endif

set mouse=a
if !has("nvim")
    if &term =~? "alacritty\\|st"
        set ttymouse=sgr
    endif

    set ttyfast
endif

set notimeout
set ttimeout
set ttimeoutlen=100

set history=10000
if !has("nvim")
    set viminfo='0,<0,h
    set viminfofile=$HOME/.vim/viminfo
else
    set shada='0,<0,h
endif

" $VIMRUNTIME/plugin
let g:loaded_2html_plugin = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_gzip = 1
let g:loaded_logiPat = 1
let g:loaded_netrw = 1
let g:loaded_netrwPlugin = 1
let g:loaded_rrhelper = 1
let g:loaded_spellfile_plugin = 1
let g:loaded_tar = 1
let g:loaded_tarPlugin = 1
let g:loaded_vimball = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zip = 1
let g:loaded_zipPlugin = 1

" man.vim, machit.vim
if !has("nvim")
    runtime ftplugin/man.vim
    set keywordprg=:Man
    autocmd FileType man setlocal nolist nonumber norelativenumber noswapfile

    packadd! matchit
endif

" dein.vim <https://github.com/Shougo/dein.vim>
let s:cache_dir = exists("$XDG_CACHE_HOME") ? expand("$XDG_CACHE_HOME") : expand("$HOME/.cache")
let s:dein_base = s:cache_dir .. "/dein"
let s:dein_src =  s:dein_base .. "/repos/github.com/Shougo/dein.vim"

if !isdirectory(s:dein_src)
    execute "!git clone https://github.com/Shougo/dein.vim" s:dein_src
endif
execute 'set runtimepath^=' .. s:dein_src

let g:dein#auto_recache = 1
let s:dein_toml_file = (exists("$XDG_CONFIG_HOME") ? expand("$XDG_CONFIG_HOME") : expand("$HOME/.config")) .. "/dein/dein.toml"
if dein#min#load_state(s:dein_base)
    call dein#begin(s:dein_base, [expand("<sfile>:p"), s:dein_toml_file])
    call dein#add(s:dein_src)
    call dein#load_toml(s:dein_toml_file)
    call dein#end()
    call dein#save_state()
endif

filetype plugin indent on
syntax enable

if dein#check_install()
    call dein#install()
endif

" keybind
map! <C-A> <S-Left>
map! <C-Z> <S-Right>
map! <C-B> <Home>
map! <C-E> <End>

autocmd FileType man nmap <buffer> <2-LeftMouse> K

set nomodeline
set secure
