[[plugins]]
if = '''!has("nvim")'''
repo = '''vim-jp/vimdoc-ja'''

[[plugins]]
repo = '''lifepillar/vim-solarized8'''
hook_add = '''
let g:solarized_italics = 0
let g:solarized_visibility = "high"'''

[[plugins]]
repo = '''https://gitlab.com/HiPhish/info.vim.git'''
hook_add = '''autocmd FileType info setlocal nonumber norelativenumber'''
